加入四種sms status code
tyr-tech-team/hawk pull request #8
Opened 2020-11-13 01:53 UTC by 1amjosh

加入四種狀態（無效的手機號碼、逾時無法送達、簡訊已過期、系統暫停服務）

2020-11-13 03:46 UTC, maxjkfc requested changes
請修正唷

2020-11-13 03:46 UTC, maxjkfc commented on status/var.go
> +	InvalidMobileNumber       = NewStatus(LevelERROR, ServiceSMS, GRPCUnknown, ActionCallAPI, "無效的手機號碼", "invalid mobile number")
這個可以有兩種解釋
1. 你在 `發送前檢查` 這個手機是無效的 那就會是 `GRPCInvalidArgument` 動作 `ActionCheck`
2. 你在` 發送後對方回傳` 手機是無效的 那就會是 `GRPCInvalidArgument` 動作 `ActionCallAPI` 
基本上 `GRPCUnknow` 偏向於你不真的不知道這是什麼，或是沒有明確錯誤才會使用

2020-11-13 03:46 UTC, maxjkfc commented on status/var.go
> +	UndeliverableAfterTimeout = NewStatus(LevelERROR, ServiceSMS, GRPCUnknown, ActionCallAPI, "逾時無法送達", "undeliverable after timeout")
1. 逾時會使用 `GRPCDeadlineExceeded`

2020-11-13 03:46 UTC, maxjkfc commented on status/var.go
> +	HasExpired                = NewStatus(LevelERROR, ServiceSMS, GRPCUnknown, ActionCallAPI, "簡訊已過期", "has expired")
這邊妳主要的含義是  簡訊發送過期，還是 簡訊的驗證碼過期？
不同含義會有不同的 參數使用 描述這樣會有點簡單，會不太知道是哪一個過期

2020-11-13 03:46 UTC, maxjkfc commented on status/var.go
> +	SuspensionOfService       = NewStatus(LevelERROR, ServiceSMS, GRPCUnknown, ActionCallAPI, "系統暫停服務", "suspend of service")
服務暫停 要使用 `GRPCUnavailable` 

另外狀態碼是不能重複的，如果有重複要重新檢視一下

2020-11-13 04:03 UTC, GaryGaGa-TYR commented on status/var.go
> +	InvalidMobileNumber       = NewStatus(LevelERROR, ServiceSMS, GRPCUnknown, ActionCallAPI, "無效的手機號碼", "invalid mobile number")
此狀態為第三方回傳

已改為GRPCInvalidArgument 動作 ActionCallAPI

2020-11-13 04:04 UTC, GaryGaGa-TYR commented on status/var.go
> +	UndeliverableAfterTimeout = NewStatus(LevelERROR, ServiceSMS, GRPCUnknown, ActionCallAPI, "逾時無法送達", "undeliverable after timeout")
已調整

2020-11-13 06:04 UTC, GaryGaGa-TYR commented on status/var.go
> +	HasExpired                = NewStatus(LevelERROR, ServiceSMS, GRPCUnknown, ActionCallAPI, "簡訊已過期", "has expired")
第三方提供發送簡訊功能中，可以設定此封簡訊過期時間

查詢已發送簡訊時，為失效簡訊的的資料回應狀態

2020-11-13 06:28 UTC, GaryGaGa-TYR commented on status/var.go
> +	HasExpired                = NewStatus(LevelERROR, ServiceSMS, GRPCUnknown, ActionCallAPI, "簡訊已過期", "has expired")
為簡訊發送過期

2020-11-13 07:20 UTC, 1amjosh commented on status/var.go
> +	SuspensionOfService       = NewStatus(LevelERROR, ServiceSMS, GRPCUnknown, ActionCallAPI, "系統暫停服務", "suspend of service")
了解！已調整狀態，將上述四種狀態統一稱為『簡訊傳送失敗』

2020-11-16 07:10 UTC, maxjkfc commented on status/var.go
> +	SuspensionOfService       = NewStatus(LevelERROR, ServiceSMS, GRPCUnknown, ActionCallAPI, "系統暫停服務", "suspend of service")
OK

2020-11-16 07:11 UTC, maxjkfc approved these changes

2020-11-16 07:11 UTC, merged